version: '3.9'

services:
  # MySQL Services
  mysql_server:
    container_name: docker_start_mysql_db
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=awan
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
      
  # Node API Services
  node_api:
    container_name: docker_start_node_api
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mysql_server

 

  
